---
project: 
  output-dir: /results
title: "05_antibody_expression_analysis"
format: html
editor: visual
---

```{r}
#| include: false
library(tidyverse)
library(viridis)
```

### Load Data

```{r}
data <- read_tsv("./../data/03_dat_aug.tsv",
                 show_col_types = FALSE)
```

### Data Analysis

```{r}
#| warning: false
data_long <- data |>
  pivot_longer(cols = c(GAD65, ZnT8, IA_2, IAA),
               names_to = "antibody", 
               values_to = "expression") |>
  group_by(antibody, timepoint, case_control) |>
  summarise(mean_expression = mean(expression,
                                   na.rm = TRUE),
            .groups = "drop")

data_long |>
  ggplot(mapping = aes(x = factor(timepoint),
                       y = mean_expression,
                       fill = case_control)) +
  geom_bar(stat = "identity",
           position = "dodge",
           alpha = 0.8,
           color = 'black') +
  facet_wrap(vars(antibody),
             scales = "free_y",
             nrow = 2) +
  labs(title = "Antibody expression across visits stratified by case/control",
       x = "Visit",
       y = "Mean Expression",
       fill = "Case/Control") +
  scale_fill_viridis(discrete = TRUE) +
  
  theme_bw() + 
  theme(legend.position = "bottom")

ggsave(width = 8,
       height = 6,
       filename = "05_plot_1.png",
       path = "./../results/")
```
