---
title: "07_HLA_allele_analysis"
format: html
editor: visual
toc: true
embed-resources: true
---

```{r}
#| include: false
library("tidyverse")
library("patchwork")
```

### Analysis

```{r, fig.height=12, fig.width=6}
#| warning: false
#| message: false
data <- read_tsv("./../data/03_dat_aug.tsv")

TCR_tidy <- data |> 
  #select(timepoint, age_visit,
  #       starts_with('HLA'), case_control) |>
  arrange(timepoint) |> 
  #pivot_longer(starts_with('HLA_'), 
  #             names_to = "allele",
  #             values_to = "subtype") |>
  mutate(allele = str_remove(allele, "(\\,1)|(\\,2)")) |>
  group_by(allele, subtype) |> 
  mutate(allele_count = n(), .groups = NULL) |>
  filter(allele_count >= 1) |>
  filter(timepoint == 4) |>
  filter(subtype != "NA") |>
  mutate(case_control = case_when(case_control == "Case" ~ 1,
                                  case_control == "Control" ~ 0))


ggplot(data = TCR_tidy,
       mapping = aes(x = allele,
                     y = subtype)) +
  geom_tile(aes(fill = case_control),
            color="#481567") + 
  theme_bw()+
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_text(angle = 90, size = 10),
        panel.grid.major.y = element_blank())+
        #panel.grid.minor = element_blank()) +
  scale_fill_gradient(low = "#20A387",
                       high = "#481567") + 
  labs(title = "Presence of HLA subtypes in case and control patients",
       x = "Allele",
       y = "Subtype",
       fill = "Case or Control")

ggsave(width = 5,
       height = 8,
       filename = "07_plot_1.png",
       path = "./../results/")
```

```{r, fig.height=10, fig.width=8}
#| warning: false
data <- read_tsv("./../data/03_dat_aug.tsv",
                 show_col_types = FALSE)

HLA_tidy <- data |> 
  filter(timepoint == 4) |> 
  #select(starts_with("HLA"),
  #       case_control,
  #       id) |>
  #pivot_longer(starts_with("HLA_"), 
  #             names_to = "allele",
  #             values_to = "subtype") |>
  mutate(allele = str_remove(allele, "(\\,1)|(\\,2)")) |>
  mutate(allele_subtype = str_c(allele,
                                subtype,
                                sep = ":")) |> 
  drop_na(allele_subtype) |> #replaced na.omit with drop_na(), all Control case would be removed
  mutate(subtype_n = 1) |>
  select(case_control,
         id,
         allele_subtype,
         subtype_n,
         allele,
         subtype) |> 
  group_by(case_control, allele_subtype) |>
  summarize(allele_n = n(), .groups = "drop") |> 
  pivot_wider(names_from = case_control,
              values_from = allele_n) |> 
  na.omit(Control, Case) |> 
  mutate(ratio = round(Case/Control, 
                       digits = 2)) |>
  select(allele_subtype, ratio)

ggplot(data = HLA_tidy,
       mapping = aes(x = reorder(allele_subtype, +ratio),
                     y = ratio)) + 
  geom_bar(stat = "identity", color = "#20A387", fill = "#20A387", alpha = 0.8) + 
  #scale_x_binned(n.breaks=2)+
  coord_flip() + 
  labs(title = "Ratio of HLA subtype occurence for case and control patients",
       x = "Allele subtype",
       y = "Ratio (Case/Control)") + 
  theme_bw() + 
  theme(panel.grid.major.y = element_blank(),
        axis.text.x= element_text(size=10),
        axis.text.y= element_text(size=7))

ggsave(width = 5,
       height = 10,
       filename = "07_plot_2.png",
       path = "./../results/")
```

```{r, fig.height=6, fig.width=12}
#| warning: false
#| message: false
data <- read_tsv("./../data/03_dat_aug.tsv")

HLA_tidy <-
  HLA_tidy |>
  ungroup() |>
  mutate(allele = str_extract(allele_subtype, "HLA[^\\:]+"),
         subtype = str_extract(allele_subtype, "\\d{4}"))


ggplot(data = HLA_tidy,
       mapping = aes(x = subtype,
                     y = allele)) +
  geom_tile(aes(fill = ratio),
            color="#481567") + 
  theme_bw()+
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_text(angle = 90, size = 10),
        panel.grid.major.y = element_blank())+
        #panel.grid.minor = element_blank()) +
  scale_fill_gradient(low = "#20A387",
                      high = "#481567") + 
  labs(title = "Ratio of HLA subtypes in case and control patients",
       x = "Allele",
       y = "Subtype",
       fill = "Case/Control")

ggsave(width = 8,
       height = 5,
       filename = "07_plot_1.png",
       path = "./../results/")
```
