---
title: "08_mca_HLA"
format: html
editor: visual
toc: true
embed-resources: true
---

```{r}
#| include: false
#| message: false
library("tidyverse")
library("FactoMineR")
```

## Load Data

```{r}
#| message: false
data <- read_tsv("./../data/03_dat_aug.tsv", 
                 show_col_types = FALSE)
```

## Analysis

### MCA HLA subtypes

```{r}
HLA_tidy <- data |> 
  filter(timepoint == 1) |>
  select(case_control,
         id,
         allele,
         subtype) |>
  mutate(allele_subtype = str_c(allele,
                                subtype,
                                sep = ":")) |>
  na.omit(allele_subtype) |>
  group_by(case_control,id, allele_subtype) |>
  summarize(subtype_n=n(), .groups = "drop") |>
  mutate(subtype_n=str_replace(subtype_n,"4","present")) |>
  pivot_wider(names_from = allele_subtype,
              values_from = subtype_n) |>
  mutate(across(everything(),
                ~replace_na(.x, "not"))) |>
  mutate(across(starts_with("HLA"), as.factor))



relevant_var <- as_vector(HLA_tidy |>
  pivot_longer(cols=starts_with("HLA"),
               names_to = "subtype",
               values_to = "presence") |>
  select(subtype,presence) |>
  filter(presence=="present") |>
  group_by(subtype) |>
  summarize(freq=n()/54) |>
  ungroup() |>
  filter(freq>=0.1) |>
  select(subtype))




HLA.active <- HLA_tidy |>
  select(all_of=relevant_var)


mca_fit <- MCA(HLA.active, graph = FALSE)


data.frame(get_eigenvalue(mca_fit)) |>
  mutate(MC=str_c("MC",seq(1,39))) |>
  ggplot(aes(x = reorder(MC, -variance.percent), y = variance.percent)) +
  geom_col(fill = "#481567", alpha = 0.8) +
  labs(title = "Variance Explained by Each MC",
       x = "MC",
       y = "Percentage of Variance explained") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90),
        panel.grid.minor = element_blank()) +
  geom_text(aes(label=round(variance.percent,1)), size=1.6, vjust=-0.7)


ggsave(width = 8,
       height = 5,
       filename = "08_plot_1.png",
       path = "./../results/")
```

None of the variables explain the variance in data enough, therefore there is no indication of specific allele subtypes that are able to conclude difference between case or control.
