---
title: "et_eller_andet"
format: html
editor: visual
---

## Load libraries

```{r}
#| message: false
library("tidyverse")
library("broom")
library("cowplot")
```

## Load Data

```{r}
#| message: false
data <- read_tsv("./../data/03_dat_aug.tsv")
```

## Analysis

### PCA HLA subtypes

```{r}
HLA_tidy <- data |> 
  filter(timepoint == 4) |>
  select(starts_with("HLA"),
         case_control,
         id) |>
  pivot_longer(starts_with("HLA_"), 
               names_to = "allele",
               values_to = "subtype") |>
  mutate(allele = str_remove(allele, "(\\,1) | (\\,2)")) |>
  mutate(allele_subtype = str_c(allele,
                                subtype,
                                sep=":")) |>
  na.omit(allele_subtype) |>
  mutate(subtype_n = 1) |>
  select(case_control,
         id,
         allele_subtype,
         subtype_n) |>
  pivot_wider(names_from = allele_subtype,
              values_from = subtype_n) |>
  mutate(across(everything(),
                ~replace_na(.x, 0))) |>
  ungroup()


pca_fit <- HLA_tidy |> 
  select(starts_with("HLA")) |>
  scale() |>
  prcomp()


pca_fit |>
  tidy(matrix = "eigenvalues") |>
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#481567", alpha = 0.8) +
  scale_x_continuous(breaks = 1:54) +
  scale_y_continuous(labels = scales::percent_format(),
                     expand = expansion(mult = c(0, 0.01))) +
  labs(title = "Variance Explained by Each PC",
       x = "PC",
       y = "Percentage") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90),
        panel.grid.minor = element_blank())
```

None of the variables describe the variance in data, therefore no indication of allele subtype can conclude difference between case or control.
