---
title: "Trying data"
author: "Bunia"
format: html
editor: visual
---

## Load libraries

```{r}
# Load libraries
library("dplyr")
library("stringr")
library("tidyr")
library("forcats")
library("ggplot2")
library("tidyverse")
library("readxl")
library("table1")
```

## Load Data

```{r}
#immu_data <- read_tsv(file = "SampleOverview.tsv",
#                      na = "N/A")
```

```{r}
#immu_data |>
#  select(sample_tags) |>
#  head(1)
```

```{r}
control_T1D <- read_excel("jci.insight.161885.sdd1.xlsx", sheet="DAISY Control")
case_T1D <- read_excel("jci.insight.161885.sdd1.xlsx", sheet="DAISY Case")
```

```{r}
case_T1D |> slice_head(n=4)
```

```{r}
case_T1D <- case_T1D |> mutate(ID = str_c("case_",
                                          rep(1:(dim(case_T1D)[1]/4),
                                              each = 4))) |> 
  relocate(ID)


control_T1D <- control_T1D |> mutate(ID = str_c("control_",
                                                rep(1:(dim(control_T1D)[1]/4),
                                                    each = 4))) |> 
  relocate(ID)


case_T1D <- case_T1D |> mutate(Type="case")
control_T1D <- control_T1D |> mutate(Type="control")


ALL_T1D <- rbind(case_T1D |> select(ID, Sex, Race, Ethnicity,Type),
                 control_T1D |> select(ID, Sex, Race, Ethnicity,Type))

ALL_T1D |>
  na.omit(ALL_T1D) |>
  mutate(Type=factor(Type)) |>
  table1(x=formula(~ Sex + Race + Ethnicity | Type),
         data=_)


ALL_T1D |> fill(everything())
?group_by()
```

```{r}

Age_DX <- case_T1D |> 
  select(ID,`Age at Dx (years)`) |> 
  filter(`Age at Dx (years)`!=is.na(`Age at Dx (years)`))


Age_1 <- case_T1D |>
  filter(`Sample Timepoint`==1) |>
  select(ID,`Age at Visit (years)`)



Time_dx <- full_join(Age_1,Age_DX,join_by(ID))
Time_dx <- Time_dx |>
  mutate(DX_time=`Age at Dx (years)` - `Age at Visit (years)`) |>
  select(ID,DX_time)


case_T1D |> left_join(Time_dx,join_by(ID))


IAAcase <- case_T1D |> group_by(ID) |> summarize(IAA_mu=mean(`IAA (nl < 0.011)`))

IAAcontrol <- control_T1D |> group_by(ID) |> summarize(IAA_mu=mean(`IAA (nl < 0.011)*`))


ggplot(IAAcase, mapping=aes(x=ID,y=IAA_mu))+
  geom_point()

ggplot(IAAcontrol, mapping=aes(x=ID,y=IAA_mu))+
  geom_point()
```

```{r}
# research PPI TCR

case_T1D |> filter(`GAD65 (nl < 20 DK Units)`!=0) |> group_by(`Sample Timepoint`) |> summarize(n=n())
```

## Sample overview

```{r}
immu_data <- read_tsv(file = "SampleOverview.tsv",
                      na = "N/A")

immu_data |>
  select(sample_tags) |>
  head(1)


control_data <- immu_data |>
  filter(str_detect(string=sample_tags, pattern="Control"))

case_data <- immu_data |>
  filter(str_detect(string=sample_tags, pattern="Case"))


case_data <- case_data |>
  mutate(subject=str_extract(sample_tags,pattern="Subject([^,]+)"))

control_data <- control_data |>
  mutate(subject=str_extract(sample_tags,pattern="Control([^,]+)"))


control_data |>
  select(sample_tags) |>
  head(1)

control_data|>
  head(5)

try <- control_data|>
  head(5)|>
  select(sample_tags)|>
  mutate(HLA=str_extract(sample_tags,pattern="HLA\\-.+\\*\\d+"),
         timepoint=str_extract(sample_tags,pattern="Timepoint\\s\\d"),
         GAD65=str_extract(sample_tags,pattern="GAD65\\s\\d+")) |>
  mutate(HLA_A=str_extract_all(HLA,pattern="HLA\\-A\\*\\d+"),
         HLA_B=str_extract_all(HLA,pattern="HLA\\-B\\*\\d+"),
         HLA_C=str_extract_all(HLA,pattern="HLA\\-C\\*\\d+"),
         HLA_DPA=str_extract_all(HLA,pattern="HLA\\-DPA\\d+\\*\\d+"),
         HLA_DPB=str_extract_all(HLA,pattern="HLA\\-DPB\\d\\*\\d+"),
         HLA_DQA=str_extract_all(HLA,pattern="HLA\\-DQA\\d\\*\\d+"),
         HLA_DQB=str_extract_all(HLA,pattern="HLA\\-DQB\\d\\*\\d+"),
         HLA_DRB=str_extract_all(HLA,pattern="HLA\\-DRB\\d\\*\\d+"))|>
  select(-sample_tags,-HLA)


```
